-- MySQL Script generated by MySQL Workbench
-- 10/26/18 17:18:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


USE `WxMemberCardServerDB` ;

-- -----------------------------------------------------
-- Table `WxMemberCardServerDB`.`WxAuthInfos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WxMemberCardServerDB`.`WxAuthInfos` ;

CREATE TABLE IF NOT EXISTS `WxMemberCardServerDB`.`WxAuthInfos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `merchantUUID` CHAR(45) NULL COMMENT '商户UUID.',
  `authAppId` CHAR(45) NULL COMMENT '授权方APPID',
  `authRefreshToken` CHAR(45) NULL COMMENT '授权方刷新TOKEN',
  `funcInfo` JSON NULL COMMENT '公众号授权给开发者的权限集列表',
  `serviceType` TINYINT NULL COMMENT '服务账号类型，0代表订阅号，1代表由历史老帐号升级后的订阅号，2代表服务号,3代表小程序',
  `nickName` VARCHAR(80) NULL COMMENT '授权方昵称',
  `headImgUrl` VARCHAR(100) NULL COMMENT '授权方头像URL.',
  `verifyType` TINYINT NULL COMMENT '授权方认证类型，-1代表未认证，0代表微信认证，1代表新浪微博认证，2代表腾讯微博认证，3代表已资质认证通过但还未通过名称认证，4代表已资质认证通过、还未通过名称认证，但通过了新浪微博认证，5代表已资质认证通过、还未通过名称认证，但通过了腾讯微博认证',
  `originId` CHAR(45) NULL COMMENT '授权方公众号的原始ID',
  `principalName` VARCHAR(80) NULL COMMENT '公众号的主体名称',
  `businessInfo` JSON NULL COMMENT '用以了解以下功能的开通状况（0代表未开通，1代表已开通）： open_store:是否开通微信门店功能 open_scan:是否开通微信扫商品功能 open_pay:是否开通微信支付功能 open_card:是否开通微信卡券功能 open_shake:是否开通微信摇一摇功能',
  `qrcodeUrl` VARCHAR(100) NULL COMMENT '本地服务器二维码图片URL.',
  `status` CHAR(45) NULL COMMENT '状态，enabled:启用，disabled:禁用。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `merchant_appid_unique` (`merchantUUID` ASC, `authAppId` ASC))
ENGINE = InnoDB
COMMENT = '微信第三方平台授权信息。';


-- -----------------------------------------------------
-- Table `WxMemberCardServerDB`.`WxOpenAccountBinds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WxMemberCardServerDB`.`WxOpenAccountBinds` ;

CREATE TABLE IF NOT EXISTS `WxMemberCardServerDB`.`WxOpenAccountBinds` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `openAppId` CHAR(45) NULL COMMENT '开放平台账号APPId.',
  `authAppId` CHAR(45) NULL COMMENT '绑定的授权方ID.',
  `authAppType` TINYINT NULL COMMENT '授权方APP类型，0为公众号，1为小程序。',
  `status` CHAR(45) NULL COMMENT '状态，enabled:启用，disabled:禁用。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `open_auth_appId` (`openAppId` ASC, `authAppId` ASC))
ENGINE = InnoDB
COMMENT = '微信开放平台账号绑定关系。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
