-- MySQL Script generated by MySQL Workbench
-- 11/09/18 16:09:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LK_WxMemberCardServerDB
-- -----------------------------------------------------
-- 微信会员卡组件数据库
DROP SCHEMA IF EXISTS `LK_WxMemberCardServerDB` ;

-- -----------------------------------------------------
-- Schema LK_WxMemberCardServerDB
--
-- 微信会员卡组件数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LK_WxMemberCardServerDB` DEFAULT CHARACTER SET utf8 ;
USE `LK_WxMemberCardServerDB` ;

-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxMemberCards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxMemberCards` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxMemberCards` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(30) NULL,
  `merchantHref` VARCHAR(150) NULL COMMENT '商户链接。',
  `merchantUUID` CHAR(30) NULL COMMENT '商户UUID',
  `title` CHAR(40) NULL COMMENT '标题。',
  `brandName` CHAR(40) NULL COMMENT '公司品牌名称。',
  `servicePhone` CHAR(45) NULL COMMENT '服务电话。',
  `description` VARCHAR(150) NULL COMMENT '卡券使用说明，字数上限为1024个汉字。',
  `notice` VARCHAR(100) NULL COMMENT '卡券使用提醒，字数上限为16个汉字',
  `logoUrl` VARCHAR(150) NULL COMMENT '微信的LOGO URL.',
  `backgroudUrl` VARCHAR(150) NULL COMMENT '背景图URL.',
  `quatity` INT NULL COMMENT '发卡数据。',
  `wxAppId` CHAR(45) NULL COMMENT '微信公众号的APPID.',
  `wxCardId` CHAR(45) NULL COMMENT '微信会员卡号ID.',
  `wxQRCodeUrl` VARCHAR(150) NULL COMMENT '微信会员卡投放二维码。',
  `status` CHAR(45) NULL COMMENT '状态，\'uncreated\':未创建，\'created\':已创建，\'audited\':已审核。',
  `refuseReason` VARCHAR(150) NULL COMMENT '拒绝原因。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `merchantUUID_UNIQUE` (`merchantUUID` ASC, `wxAppId` ASC))
ENGINE = InnoDB
COMMENT = '微信会员卡类型。';


-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxMemberCardItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxMemberCardItems` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxMemberCardItems` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `wxCardId` CHAR(45) NULL COMMENT '微信会员卡ID.',
  `wxMemberCardCode` CHAR(45) NULL COMMENT '微信会员卡CODE码。',
  `wxMemberShipNo` CHAR(45) NULL COMMENT '微信会员卡号，默认与CODE相同。',
  `openId` VARCHAR(45) NULL COMMENT '微信公众号用户OPENID.',
  `unionId` VARCHAR(45) NULL COMMENT '微信union唯一ID.',
  `mobile` VARCHAR(45) NULL COMMENT '手机号码。',
  `name` VARCHAR(45) NULL COMMENT '姓名。',
  `nickname` VARCHAR(45) NULL COMMENT '昵称。',
  `sex` TINYINT(1) NULL COMMENT '性别，1:男，0:女。',
  `birthday` DATE NULL COMMENT '生日。',
  `ownerCardId` VARCHAR(45) NULL COMMENT '内部卡号ID.',
  `ownerCardUUID` VARCHAR(45) NULL COMMENT '内部会员卡UUID.',
  `status` CHAR(45) NULL COMMENT '当前用户的会员卡状态， created:已创建，normal:正常 expire:已过期 gifting:转赠中 giftSuced:转赠成功 giftTimeout:转赠超时 deleted:已删除，unavaliabled:已失效,',
  `isActived` TINYINT(2) NULL COMMENT '该卡是否已经被激活，1表示已经被激活，0表示未被激活',
  `createdAt` TIMESTAMP(0) NULL COMMENT '创建时间。',
  `modifiedAt` TIMESTAMP(0) NULL COMMENT '修改时间。',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `cardId_openId_unique` (`wxCardId` ASC, `openId` ASC))
ENGINE = InnoDB
COMMENT = '微信会员卡具体条目信息。';


-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxImages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxImages` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxImages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `orignUrl` VARCHAR(150) NULL COMMENT '原始URL.',
  `wxResourceUrl` VARCHAR(150) NULL COMMENT '微信资源URL.',
  `appId` CHAR(45) NULL COMMENT '微信公众号APPID.',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '微信图片映射表。';


-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxSubMerchants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxSubMerchants` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxSubMerchants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `merchantHref` VARCHAR(150) NULL COMMENT '商户链接。',
  `merchantUUID` CHAR(45) NULL COMMENT '商户UUID.',
  `brandName` VARCHAR(45) NULL COMMENT '品牌名称。',
  `logoUrl` VARCHAR(150) NULL COMMENT 'logo的URL。',
  `protocolUrl` VARCHAR(150) NULL COMMENT '本地授权函URL.',
  `protocolMediaId` VARCHAR(150) NULL COMMENT '授权函MEDIA的ID.',
  `protocolEndAt` TIMESTAMP(0) NULL COMMENT '授权函截止时间。',
  `agreementUrl` VARCHAR(150) NULL COMMENT '营业执照或个体工商户营业执照彩照或扫描件',
  `agreementMediaId` VARCHAR(150) NULL COMMENT '营业执照或个体工商户营业执照彩照或扫描件MediaId',
  `operatorUrl` VARCHAR(150) NULL COMMENT '营业执照内登记的经营者身份证彩照或扫描件,url.',
  `operatorMediaId` VARCHAR(150) NULL COMMENT '营业执照内登记的经营者身份证彩照或扫描件,mediaId.',
  `primaryCategoryId` INT NULL COMMENT '一级类目id',
  `secondaryCategoryId` INT NULL COMMENT '二级类目id',
  `wxAppId` CHAR(45) NULL COMMENT '公众号母商户APPID.',
  `wxSubMerchantId` VARCHAR(45) NULL COMMENT '微信子商户ID.',
  `wxSubAppId` VARCHAR(45) NULL COMMENT '微信子商户公众号APP ID.',
  `status` CHAR(45) NULL COMMENT '状态，created:已创建,checking: 审核中, approved : 已通过,rejected:被驳回, expired,协议已过期',
  `rejectReason` VARCHAR(150) NULL COMMENT '驳回的原因',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '微信第三方代制卡劵子商户信息。';


-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxAuthInfos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxAuthInfos` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxAuthInfos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `merchantUUID` CHAR(45) NULL COMMENT '商户UUID.',
  `authAppId` CHAR(45) NULL COMMENT '授权方APPID',
  `authRefreshToken` VARCHAR(200) NULL COMMENT '授权方刷新TOKEN',
  `serviceType` TINYINT NULL COMMENT '服务账号类型，0代表订阅号，1代表由历史老帐号升级后的订阅号，2代表服务号,3代表小程序',
  `nickName` VARCHAR(180) NULL COMMENT '授权方昵称',
  `headImgUrl` VARCHAR(255) NULL COMMENT '授权方头像URL.',
  `verifyType` TINYINT NULL COMMENT '授权方认证类型，-1代表未认证，0代表微信认证，1代表新浪微博认证，2代表腾讯微博认证，3代表已资质认证通过但还未通过名称认证，4代表已资质认证通过、还未通过名称认证，但通过了新浪微博认证，5代表已资质认证通过、还未通过名称认证，但通过了腾讯微博认证',
  `originId` CHAR(45) NULL COMMENT '授权方公众号的原始ID',
  `principalName` VARCHAR(180) NULL COMMENT '公众号的主体名称',
  `qrcodeUrl` VARCHAR(255) NULL COMMENT '本地服务器二维码图片URL.',
  `status` CHAR(45) NULL COMMENT '状态，enabled:启用，disabled:禁用。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `merchant_appid_unique` (`merchantUUID` ASC, `authAppId` ASC))
ENGINE = InnoDB
COMMENT = '微信第三方平台授权信息。';


-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxOpenAccountBinds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxOpenAccountBinds` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxOpenAccountBinds` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `openAppId` CHAR(45) NULL COMMENT '开放平台账号APPId.',
  `authAppId` CHAR(45) NULL COMMENT '绑定的授权方ID.',
  `status` CHAR(45) NULL COMMENT '状态，enabled:启用，disabled:禁用。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `open_auth_appId` (`openAppId` ASC, `authAppId` ASC))
ENGINE = InnoDB
COMMENT = '微信开放平台账号绑定关系。';


-- -----------------------------------------------------
-- Table `LK_WxMemberCardServerDB`.`WxMiniPrgVersions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LK_WxMemberCardServerDB`.`WxMiniPrgVersions` ;

CREATE TABLE IF NOT EXISTS `LK_WxMemberCardServerDB`.`WxMiniPrgVersions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `merchantUUID` CHAR(45) NULL COMMENT '小程序所属商户UUID.',
  `appId` CHAR(45) NULL COMMENT '小程序APPID.',
  `templateId` INT NULL COMMENT '代码模板ID.',
  `userCodeVersion` VARCHAR(45) NULL COMMENT '用户代码版本。',
  `userCodeDesc` VARCHAR(45) NULL COMMENT '用户代码描述。',
  `customerExtJson` JSON NULL COMMENT '用户自定义扩展配置。',
  `auditInfo` JSON NULL COMMENT '提交审核配置的信息。',
  `auditid` INT NULL COMMENT '审核单ID.',
  `status` CHAR(45) NULL COMMENT '版本状态，created:已创建，uploaded:已上传，commited:已提交，audited:已审核，auditFailed:审核失败，released:已发布。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `appId_templateId_idx` (`appId` ASC, `templateId` ASC))
ENGINE = InnoDB
COMMENT = '微信小程序版本管理。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
