-- MySQL Script generated by MySQL Workbench
-- 09/03/18 14:26:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


USE `WxMemberCardServerDB` ;

-- -----------------------------------------------------
-- Table `WxMemberCardServerDB`.`WxSubMerchants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WxMemberCardServerDB`.`WxSubMerchants` ;

CREATE TABLE IF NOT EXISTS `WxMemberCardServerDB`.`WxSubMerchants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(45) NULL,
  `merchantHref` VARCHAR(150) NULL COMMENT '商户链接。',
  `merchantUUID` CHAR(45) NULL COMMENT '商户UUID.',
  `brandName` VARCHAR(45) NULL COMMENT '品牌名称。',
  `logoUrl` VARCHAR(150) NULL COMMENT 'logo的URL。',
  `protocolUrl` VARCHAR(150) NULL COMMENT '本地授权函URL.',
  `protocolMediaId` CHAR(45) NULL COMMENT '授权函MEDIA的ID.',
  `protocolEndAt` TIMESTAMP(0) NULL COMMENT '授权函截止时间。',
  `agreementUrl` VARCHAR(150) NULL COMMENT '营业执照或个体工商户营业执照彩照或扫描件',
  `agreementMediaId` CHAR(45) NULL COMMENT '营业执照或个体工商户营业执照彩照或扫描件MediaId',
  `operatorUrl` VARCHAR(150) NULL COMMENT '营业执照内登记的经营者身份证彩照或扫描件,url.',
  `operatorMediaId` VARCHAR(45) NULL COMMENT '营业执照内登记的经营者身份证彩照或扫描件,mediaId.',
  `primaryCategoryId` INT NULL COMMENT '一级类目id',
  `secondaryCategoryId` INT NULL COMMENT '二级类目id',
  `wxSubMerchantId` VARCHAR(45) NULL COMMENT '微信子商户ID.',
  `wxSubAppId` VARCHAR(45) NULL COMMENT '微信子商户公众号APP ID.',
  `status` CHAR(45) NULL COMMENT '状态，created:已创建,checking: 审核中, approved : 已通过,rejected:被驳回, expired,协议已过期',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '微信第三方代制卡劵子商户信息。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
